# Learn more about this file at 'https://www.gitpod.io/docs/references/gitpod-yml'
#
# This '.gitpod.yml' file when placed at the root of a project instructs
# Gitpod how to prepare & build the project, start development environments
# and configure continuous prebuilds. Prebuilds when enabled builds a project
# like a CI server so you can start coding right away - no more waiting for
# dependencies to download and builds to finish when reviewing pull-requests
# or hacking on something new.
#
# With Gitpod you can develop software from any device (even iPads) via
# desktop or browser based versions of VS Code or any JetBrains IDE and
# customise it to your individual needs - from themes to extensions, you
# have full control.

#vscode:
#  extensions:
#    - 42Crunch.vscode-openapi

tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -qq awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - 42Crunch.vscode-openapi
